// src/vulkan_logic/pipeline.rs

use anyhow::{anyhow, Result};
use ash::vk;
use std::ffi::CStr;
use std::fs::File;
use std::io::Read;

use super::context::VulkanContext;
use crate::vulkan_logic::vertex_setup::VertexSetup;
use crate::backface_cull_config::{DEFAULT_CULL_MODE, CULL_MODE_NONE, CULL_MODE_CW};

/// Push constants are small packets of data sent directly to the GPU registers.
/// They are incredibly fast to update but very limited in size (usually 128 bytes max).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PushConstants {
    pub view_proj: glam::Mat4, 
    pub model: glam::Mat4,     
    // NEW: Used by the main pass to transform pixels into the light's point of view
    // so we can compare their depth against the shadow map.
    pub light_space_matrix: glam::Mat4, 
}

/// Holds all the pipeline configurations needed for both regular rendering and shadows.
pub struct VulkanPipeline {
    pub layout: vk::PipelineLayout,
    pub graphics_pipeline: vk::Pipeline,
    pub shadow_pipeline: vk::Pipeline, // NEW: Dedicated pipeline for rendering depth maps
    pub descriptor_set_layout: vk::DescriptorSetLayout, 
}

impl VulkanPipeline {
    /// Constructs all pipelines required by the engine.
    pub fn new(context: &VulkanContext, main_render_pass: vk::RenderPass, shadow_render_pass: vk::RenderPass) -> Result<Self> {
        
        // 1. Read shader binaries from disk
        // (Ensure you run glslc to compile these after updating the source files!)
        let vert_shader_code = Self::read_shader_file("src/vulkan_logic/compiled_shaders/triangle.vert.spv")?;
        let frag_shader_code = Self::read_shader_file("src/vulkan_logic/compiled_shaders/triangle.frag.spv")?;
        let shadow_vert_code = Self::read_shader_file("src/vulkan_logic/compiled_shaders/shadow.vert.spv")?;

        // 2. Create Vulkan shader modules from the loaded bytecode
        let vert_shader_module = Self::create_shader_module(&context.device, &vert_shader_code)?;
        let frag_shader_module = Self::create_shader_module(&context.device, &frag_shader_code)?;
        let shadow_vert_module = Self::create_shader_module(&context.device, &shadow_vert_code)?;

        // The entry point for all our shaders is "main"
        let main_function_name = unsafe { CStr::from_bytes_with_nul_unchecked(b"main\0") };

        // --- DESCRIPTOR SET LAYOUT ---
        // This acts as a blueprint telling the pipeline what resources (UBOs, textures) will be bound.
        
        // Binding 0: Uniform Buffer (Lighting parameters and camera data)
        let ubo_binding = vk::DescriptorSetLayoutBinding::default()
            .binding(0)
            .descriptor_type(vk::DescriptorType::UNIFORM_BUFFER)
            .descriptor_count(1)
            .stage_flags(vk::ShaderStageFlags::VERTEX | vk::ShaderStageFlags::FRAGMENT);

        // Binding 1: Shadow Map Texture Sampler (Reads the depth map generated by the shadow pass)
        let sampler_binding = vk::DescriptorSetLayoutBinding::default()
            .binding(1)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .descriptor_count(1)
            .stage_flags(vk::ShaderStageFlags::FRAGMENT);

        let bindings = [ubo_binding, sampler_binding];
        let layout_info = vk::DescriptorSetLayoutCreateInfo::default()
            .bindings(&bindings);

        let descriptor_set_layout = unsafe { context.device.create_descriptor_set_layout(&layout_info, None) }
            .map_err(|e| anyhow!("Failed to create descriptor set layout: {}", e))?;

        // --- PIPELINE LAYOUT ---
        // Combines the descriptor set layout with push constants to form the complete signature.
        
        let push_constant_range = vk::PushConstantRange::default()
            .stage_flags(vk::ShaderStageFlags::VERTEX)
            .offset(0)
            .size(std::mem::size_of::<PushConstants>() as u32); 

        let pipeline_layout_info = vk::PipelineLayoutCreateInfo::default()
            .set_layouts(std::slice::from_ref(&descriptor_set_layout))
            .push_constant_ranges(std::slice::from_ref(&push_constant_range));

        let layout = unsafe { context.device.create_pipeline_layout(&pipeline_layout_info, None) }
            .map_err(|e| anyhow!("Failed to create pipeline layout: {}", e))?;

        // --- SHARED PIPELINE CONFIGURATION ---
        // Settings that apply to both the shadow pass and the main rendering pass.
        
        let binding_descriptions = [VertexSetup::get_binding_description()];
        let attribute_descriptions = VertexSetup::get_attribute_descriptions();
        
        let vertex_input_info = vk::PipelineVertexInputStateCreateInfo::default()
            .vertex_binding_descriptions(&binding_descriptions)
            .vertex_attribute_descriptions(&attribute_descriptions);

        let input_assembly = vk::PipelineInputAssemblyStateCreateInfo::default()
            .topology(vk::PrimitiveTopology::TRIANGLE_LIST)
            .primitive_restart_enable(false);

        let dynamic_states = [vk::DynamicState::VIEWPORT, vk::DynamicState::SCISSOR];
        let dynamic_state = vk::PipelineDynamicStateCreateInfo::default()
            .dynamic_states(&dynamic_states);

        let viewport_state = vk::PipelineViewportStateCreateInfo::default()
            .viewport_count(1).scissor_count(1);

        let multisampling = vk::PipelineMultisampleStateCreateInfo::default()
            .sample_shading_enable(false)
            .rasterization_samples(vk::SampleCountFlags::TYPE_1);

        // --- 1. MAIN GRAPHICS PIPELINE ---
        
        let main_shader_stages = [
            vk::PipelineShaderStageCreateInfo::default()
                .stage(vk::ShaderStageFlags::VERTEX).module(vert_shader_module).name(main_function_name),
            vk::PipelineShaderStageCreateInfo::default()
                .stage(vk::ShaderStageFlags::FRAGMENT).module(frag_shader_module).name(main_function_name),
        ];

        let (cull_mode, front_face) = match DEFAULT_CULL_MODE {
            CULL_MODE_NONE => (vk::CullModeFlags::NONE, vk::FrontFace::COUNTER_CLOCKWISE),
            CULL_MODE_CW => (vk::CullModeFlags::BACK, vk::FrontFace::CLOCKWISE),
            _ => (vk::CullModeFlags::BACK, vk::FrontFace::COUNTER_CLOCKWISE), 
        };

        let main_rasterizer = vk::PipelineRasterizationStateCreateInfo::default()
            .depth_clamp_enable(false).rasterizer_discard_enable(false).polygon_mode(vk::PolygonMode::FILL)
            .line_width(1.0).cull_mode(cull_mode).front_face(front_face).depth_bias_enable(false);

        let main_depth_stencil = vk::PipelineDepthStencilStateCreateInfo::default()
            .depth_test_enable(true).depth_write_enable(true).depth_compare_op(vk::CompareOp::LESS)
            .depth_bounds_test_enable(false).stencil_test_enable(false);

        let color_blend_attachment = vk::PipelineColorBlendAttachmentState::default()
            .color_write_mask(vk::ColorComponentFlags::R | vk::ColorComponentFlags::G | vk::ColorComponentFlags::B | vk::ColorComponentFlags::A)
            .blend_enable(false);

        let color_blending = vk::PipelineColorBlendStateCreateInfo::default()
            .logic_op_enable(false).attachments(std::slice::from_ref(&color_blend_attachment));

        let main_pipeline_info = vk::GraphicsPipelineCreateInfo::default()
            .stages(&main_shader_stages)
            .vertex_input_state(&vertex_input_info)
            .input_assembly_state(&input_assembly)
            .viewport_state(&viewport_state)
            .rasterization_state(&main_rasterizer)
            .multisample_state(&multisampling)
            .depth_stencil_state(&main_depth_stencil) 
            .color_blend_state(&color_blending)
            .dynamic_state(&dynamic_state)
            .layout(layout)
            .render_pass(main_render_pass)
            .subpass(0);

        // --- 2. SHADOW PIPELINE ---
        
        // Shadows only need a vertex shader. The fragment depth is automatically written.
        let shadow_shader_stages = [
            vk::PipelineShaderStageCreateInfo::default()
                .stage(vk::ShaderStageFlags::VERTEX).module(shadow_vert_module).name(main_function_name),
        ];

        let shadow_rasterizer = vk::PipelineRasterizationStateCreateInfo::default()
            .depth_clamp_enable(false).rasterizer_discard_enable(false).polygon_mode(vk::PolygonMode::FILL)
            .line_width(1.0)
            .cull_mode(vk::CullModeFlags::NONE) 
            .front_face(vk::FrontFace::COUNTER_CLOCKWISE)
            .depth_bias_enable(true) // Crucial for shadows to prevent Z-fighting (shadow acne)
            .depth_bias_constant_factor(1.25)
            .depth_bias_slope_factor(1.75);

        let shadow_depth_stencil = vk::PipelineDepthStencilStateCreateInfo::default()
            .depth_test_enable(true).depth_write_enable(true).depth_compare_op(vk::CompareOp::LESS)
            .depth_bounds_test_enable(false).stencil_test_enable(false);

        // FIXED: Instead of using .attachment_count(0) which is invalid as a builder method,
        // we provide an empty slice &[] to .attachments() which informs the builder that the count is 0.
        // This is correct because the shadow pass outputs depth, not color!
        let shadow_color_blending = vk::PipelineColorBlendStateCreateInfo::default()
            .logic_op_enable(false)
            .attachments(&[]);

        let shadow_pipeline_info = vk::GraphicsPipelineCreateInfo::default()
            .stages(&shadow_shader_stages)
            .vertex_input_state(&vertex_input_info)
            .input_assembly_state(&input_assembly)
            .viewport_state(&viewport_state)
            .rasterization_state(&shadow_rasterizer)
            .multisample_state(&multisampling)
            .depth_stencil_state(&shadow_depth_stencil)
            .color_blend_state(&shadow_color_blending)
            .dynamic_state(&dynamic_state)
            .layout(layout)
            .render_pass(shadow_render_pass)
            .subpass(0);

        // --- 3. BATCH PIPELINE CREATION ---
        // Create both the main and shadow pipelines in a single call for better driver optimization.
        
        let pipelines = unsafe {
            context.device.create_graphics_pipelines(
                vk::PipelineCache::null(), 
                &[main_pipeline_info, shadow_pipeline_info], 
                None
            )
        }.map_err(|e| anyhow!("Failed to create pipelines: {:?}", e.1))?;

        // Cleanup shader modules from RAM; they have been compiled into the pipeline on the GPU.
        unsafe {
            context.device.destroy_shader_module(vert_shader_module, None);
            context.device.destroy_shader_module(frag_shader_module, None);
            context.device.destroy_shader_module(shadow_vert_module, None);
        }

        Ok(Self { 
            layout, 
            graphics_pipeline: pipelines[0], 
            shadow_pipeline: pipelines[1], 
            descriptor_set_layout 
        })
    }

    /// Helper to read a compiled SPIR-V shader file from disk into a byte vector.
    fn read_shader_file(path: &str) -> Result<Vec<u8>> {
        let mut file = File::open(path).map_err(|e| anyhow!("Failed to open shader file at {}: {}", path, e))?;
        let mut buffer = Vec::new();
        file.read_to_end(&mut buffer).map_err(|e| anyhow!("Failed to read shader file: {}", e))?;
        Ok(buffer)
    }

    /// Helper to create a Vulkan Shader Module from raw SPIR-V bytes.
    fn create_shader_module(device: &ash::Device, code: &[u8]) -> Result<vk::ShaderModule> {
        // Enforce proper alignment as required by Vulkan API
        let (prefix, code_u32, suffix) = unsafe { code.align_to::<u32>() };
        if !prefix.is_empty() || !suffix.is_empty() { 
            return Err(anyhow!("Shader bytecode misaligned")); 
        }
        let create_info = vk::ShaderModuleCreateInfo::default().code(code_u32);
        unsafe { device.create_shader_module(&create_info, None) }
            .map_err(|e| anyhow!("Failed to create shader module: {}", e))
    }

    /// Cleans up pipeline resources during shutdown.
    pub fn destroy(&mut self, device: &ash::Device) {
        unsafe {
            device.destroy_descriptor_set_layout(self.descriptor_set_layout, None);
            device.destroy_pipeline(self.graphics_pipeline, None);
            device.destroy_pipeline(self.shadow_pipeline, None);
            device.destroy_pipeline_layout(self.layout, None);
        }
    }
}